version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build-and-lint:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint
          command: npm run lint

workflows:
  sample:
    jobs:
      - build-and-lint
